### ISSUE TITLE
Annoying behaviour 

### ISSUE THREAD

**Issue by bi6o** [ajaxtown/linkcast#13]
Upon trying to click the comments/like/etc... the icon is so small that the user ends up clicking somewhere else, which leads to the link opening and the extension to be unfocused (closed). 

Consider making the icons bigger, or having a wrapper around them so that a miss-click does not lead to that result. 

Included an image to show which icons I mean specifically. I have no image editor but they are clear (the ones under the link title)

![screen shot 2017-08-01 at 2 28 23 pm](https://user-images.githubusercontent.com/15965988/28825358-27842f36-76c6-11e7-880e-7dfdccfe0e21.png)

**Comment by abhisaha1** [comment]
@fleshsword has created awesome designs - [check this](https://github.com/ajaxtown/linkcast/issues/12). Excited to give those designs a life.
