### ISSUE TITLE
Clicking on the notification opens google

### ISSUE THREAD

**Issue by farokojil** [ajaxtown/linkcast#2]
Expected behaviour: opens the posted link

**Comment by abhisaha1** [comment]
This is a bug. Right now the server sends only the number of notifications and not the notification data. This needs to be changed.

**Comment by bi6o** [comment]
Could be that when the user clicks the notification the link opens and the link owner's name would be injected to the page that has opened

**Comment by abhisaha1** [comment]
Injections wont be a good idea. Each page will have different markup and and a site using react might stop working due to the injection.

**Comment by bi6o** [comment]
Oh here is where you explained that injection won't work with React not on the "Inject share button" issue
