### ISSUE TITLE
Setting main group is not being persisted

### ISSUE THREAD

**Issue by farokojil** [ajaxtown/linkcast#3]
![image](https://user-images.githubusercontent.com/1919333/27443406-33f873ca-5773-11e7-9304-3879324e80b8.png)

After each restart, The main group will fall back to Global

**Comment by abhisaha1** [comment]
This is related to OS/Browser. Keeping this on hold until I can recreate this.

**Comment by abhisaha1** [comment]
@farokojil  Can you check if this is still an issue ?

**Comment by farokojil** [comment]
So you removed the `Make Default` button. but I tried to set it through the wall dropdown .. will check in next couple of days if it happens again, otherwise  will close the issue :wink:

**Comment by farokojil** [comment]
I just restarted my laptop and it seems to work fine now
