### ISSUE TITLE
Feature: Comments on posts

### ISSUE THREAD

**Issue by farokojil** [ajaxtown/linkcast#4]
Comments on each post that would work like replies in Slack. An indicator of the number of comments will be on each post and clicking on the comments would expand the list of comments with an input box to add a new one

![image](https://user-images.githubusercontent.com/1919333/27443527-a656c05c-5773-11e7-9ef5-449ca18da334.png)

**Comment by abhisaha1** [comment]
Comments will not have replies. We would not want threaded replies because that needs a lot of space. So we can have single-level comments.

So, the below wont work out.
```
-Comment 1
   -Reply to comment 1
       - Reply to the reply of comment1
```
This can work
```
-comment 1
-comment 2
-comment 3
```

**Comment by farokojil** [comment]
:+1: threads are totally unnecessary
