### ISSUE TITLE
Feature request: inject share button

### ISSUE THREAD

**Issue by bi6o** [ajaxtown/linkcast#5]
The idea is to have a button in each page. On click, this button would pop-up a model with the same "Add Link" form from the extension. The user will be able to add a link from that form straight into the extension.

**Comment by abhisaha1** [comment]
Its important to figure out the position of the button as this might block some content beneath. Also not all users might like this as they would not want extra option in the page which is not related to the website.

There should be an option in the preference. Activating that option will display the button on the every site. Would this be a better way of achieving this ?

**Comment by bi6o** [comment]
What I was thinking is that the button could have an overlay of .7 and would be draggable. Also, there could be a switch in the extension to turn on/off that button
