### ISSUE TITLE
Feature request: filter all posts by a specific user

### ISSUE THREAD

**Issue by bi6o** [ajaxtown/linkcast#7]
Choose a user (somehow), and with a click a new tab would open with the selected user's links. Also would be cool to be able to filter which group the selected user posted in (but the user who selected has to be in the selected group to view the links there). The dropdown menu to choose which group the selected user has posted in could have the same location as the dropdown menu to choose the group in the main "Wall" tab.

**Comment by abhisaha1** [comment]
I am considering a profile page of user where you get to see for which you have permissions. So it wont be just links, but also user's profile pic with a bio. This will just bring some engagement. What do you think ?

**Comment by bi6o** [comment]
That would be a bigger step in the right direction than what I suggested. Can't wait to see it implemented
